name: project_redpoint
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  glob: ^2.1.2
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2
  supabase: ^1.11.11
  supabase_flutter: ^1.10.25

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.8
  riverpod_lint: ^2.3.6

flutter:
  assets:
    - img/
    - img/merch/
    - img/promo/

  uses-material-design: true